name: aula2023
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.*
  - livereload==2.6.*
  - numpy
  - matplotlib
  - jupyterlab
  - jupyter-book
  - sphinxcontrib-bibtex
  # Geo stuff
  - harmonica
  - verde
  - boule
  - ensaio
  - pooch
  - choclo
  - pygmt
  - gmt
  - xarray
  - netcdf4
  - pykdtree
