name: aula2023
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.*
  - pip
  - livereload==2.6.*
  - numpy
  - matplotlib
  - jupyterlab
  - jupyter-book
  - sphinxcontrib-bibtex
  - jupyterlab-myst
  - ipywidgets
  # Geo stuff
  - harmonica
  - boule
  - ensaio
  - pooch
  - choclo
  - pygmt
  - gmt
  - pyproj
  - xarray
  - xrft
  - netcdf4
  - pykdtree
  - pip:
    - git+https://github.com/fatiando/verde
